In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Write TensorFlow code to create a constant tensor with the values [1, 2, 3].

In [2]:
tensor = tf.constant([1, 2, 3])
print(tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


Given two tensors a = tf.constant([2, 4, 6]) and b = tf.constant([1, 2, 3]), write TensorFlow code to perform element-wise multiplication.

In [3]:
a = tf.constant([2, 4, 6])
b = tf.constant([1, 2, 3])
c = a*b
print(c)

tf.Tensor([ 2  8 18], shape=(3,), dtype=int32)


Take a 1D tensor x = tf.constant([1, 2, 3, 4, 5, 6]) and reshape it into a 2D tensor with 2 rows and 3 columns.

In [4]:
x = tf.constant([1, 2, 3, 4, 5, 6])
x = tf.reshape(x, [2, 3])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Given a 2D tensor matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), extract the middle column using TensorFlow.

In [5]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
middle = matrix[:, 1]
print(middle)

tf.Tensor([2 5 8], shape=(3,), dtype=int32)


Initialize a TensorFlow variable weights with a 3x3 matrix of random values.

In [6]:
weights = tf.Variable(tf.random.normal([3,3]))
print(weights)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.24172407,  0.11338052, -1.2534821 ],
       [-0.6338133 , -1.4279194 , -1.1238059 ],
       [-0.09322572,  0.9517461 , -0.47436583]], dtype=float32)>


Write TensorFlow code to calculate the element-wise square root of a tensor.

In [7]:
a = tf.constant([4.0, 9.0, 16.0])
b = tf.sqrt(a)
print(b)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
